{% set version = "0.9.6" %}

package:
  name: libcmaes
  version: {{ version }}

source:
  fn: libcmaes-{{ version }}.tar.gz
  url: https://github.com/beniz/libcmaes/archive/{{ version }}.tar.gz
  sha256: 1b23e53eb4acb123348e7d00dfdd7c7699c513950347fcde7425376ad333f6c5
  #patches:
  #  # https://github.com/beniz/libcmaes/pull/149
  #  - py3k.patch

build:
  number: 0
  # does not build with vc9
  skip: true  # [win and py<35]

requirements:
  build:
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - cmake  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - boost 1.64.*
    - eigen
    - numpy        # [not (win and py36)]
    - numpy         # [win and py36]
  run:
    - python
    - {{ pin_compatible('numpy') }}   # [not (win and py36)]
    - {{ pin_compatible('numpy') }}   # [win and py36]
    - boost 1.64.*

test:
  commands:
    - test -f ${PREFIX}/include/libcmaes/cmaes.h  # [unix]
    - test -f ${PREFIX}/lib/libcmaes${SHLIB_EXT}  # [unix]
  imports:
    - lcmaes  # [linux]

about:
  home: https://github.com/beniz/libcmaes
  license: LGPL3
  license_file: COPYING
  summary: High performance blackbox stochastic optimization using the CMA-ES algorithm

extra:
  recipe-maintainers:
    - jschueller
