{% set version = "0.9.6" %}

package:
  name: libcmaes
  version: {{ version }}

source:
  fn: libcmaes-{{ version }}.tar.gz
  url: https://github.com/beniz/libcmaes/archive/{{ version }}.tar.gz
  sha256: 1b23e53eb4acb123348e7d00dfdd7c7699c513950347fcde7425376ad333f6c5
  patches:
    - dynamic_lookup.patch  # [osx]

build:
  number: 0
  # does not build with vc9
  skip: true  # [win and py<35]

requirements:
  build:
      #- autoconf  # [unix]
      #- automake  # [unix]
    - libtool  # [unix]
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - cmake >=3.12.1
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - boost
    - eigen
    - numpy
  run:
    - python
    - numpy
    - boost

test:
  commands:
    - test -f ${PREFIX}/include/libcmaes/cmaes.h  # [unix]
    - test -f ${PREFIX}/lib/libcmaes${SHLIB_EXT}  # [unix]
  imports:
    - lcmaes

about:
  home: https://github.com/beniz/libcmaes
  license: LGPL3
  license_file: COPYING
  summary: High performance blackbox stochastic optimization using the CMA-ES algorithm

extra:
  recipe-maintainers:
    - jschueller
