travis:
  secure:
    BINSTAR_TOKEN: oaXjqu5H6j9FC1a01JNYpLn0ms7nSqRVtn+LOilKLfLjnom5otcNhwplcvG/BC06yfZBt+18VbIqqZw+thOTSuuwgsfVHtwsQTu9IPYHPcuRD3xWY3LbiFq3agh27CVCXrQvLxKukZmppE3ZYZvCG+xJw+mgYfmdm0KAmgJXfOPJ14Ev6bZREkCdfLQRCVaKOQ8++zu8zi2cO0gnawhsKvA05WI4rVxIGZu+Oj8yOD+Kpj07JlmpwcCKOygPjJnq0uZ64H/M9aGShyLGT8Ff+xwyDwYjphqNihNKK97lWm6Ftkrne/nXriIRcp6R19scxS1jU88sJ8Q41F7Qp7HzI99rMgv5lHVZu0Yv5p0C2YeGdDp8W0x7+yIW/GyENo5k5JLX98ywHcwEj+oJoQrtclRaxIF1CQzkjyCS3RhX/fzSVN71bHtgpRjVUGP9/pEKIlSwZ92fCQ4AaeIt2ZaEwKEc/Wi8zOBnovQZgVZ5MRVrDdj55phG1fSDqWK4ja5+/skaXUvGy5LtHKzk3WiiUuoidJmpcEToIqRaCQ1lV9YE5uk3iNzAUZlEYplOSb1qO6P2Wp3rR1pc2wS23ah+CW/FtGeK7020kIe5QaJSA02t2OEgG/ORfFEVhEZzGjPAeWK5dBJyl5gemfc/wdP+BUGVUDj/zXCFqq2PTpd8dzk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
