travis:
  secure:
    BINSTAR_TOKEN: tECXtDOzaIjWCD12KrmoljucNU2ltvTuqAFj3+7yIpueWHIeEf5CZ26bgMHkZAse2BtCc/0nvJQMONZ+2sFXAd+OjQjLKVVGsNRG6igEQR0B0T1AbXy1wOfE61b4WII5BNroocSqJvhgF0qpv1aGtb21QXtyBuC6zYP+T0rDZKO0O0KEcQXM7VCB6Ocp1BZxmLUtf0ZEgnvFlZq+nlfQlU0rXEyr5bx396oiAUah3fWlowyqRCYgIMaisd5K69y+xfFeKY2q1dQ32V+Qj4kzOWzySfioszc0eE54fmCp7Xv9btuAcS3R5afFK7rYjlafj6ftHMi+al3NTyKvL88dIQx9VE4EbRBQRZIrwQRFZyveYJpCbo5Ox6leApucWMyTTihpXctHYt96lFyLnvvWwmgSWmQdNTWAnNFL5/OfoW4QbAsGXq7ZSG9SXqaPd1xCYwx5todWKt+DhjDtHADfCQjbuECgtn25l+L/X+wQcxCaxpqgCNIfKKjwzX+jzPYBhSkiyfBCOWr0NfTYXjYEg13QZfr3vzwf2XDTC2Z5E8VyNw5nSPJvHJRUXcqI9ky412KZ40CwW5UPUPba8PWlc8SogcPsgq9yBIGTKwXJREaff5d3+rup/P5APmgLmbToZQGtJA9Y1f07xxICGf/hEUx+Qynl7bF6Jsod3spUiA0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
